// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/me/": {
            "get": {
                "description": "Past GitHub Api key to perform request",
                "tags": [
                    "GitHub API"
                ],
                "summary": "Get User Info from GitHub API",
                "responses": {}
            }
        },
        "/api/v1/repo/create/": {
            "post": {
                "tags": [
                    "GitHub API"
                ],
                "responses": {}
            }
        },
        "/api/v1/repo/detail/": {
            "get": {
                "tags": [
                    "GitHub API"
                ],
                "responses": {}
            }
        },
        "/api/v1/repo/list/": {
            "get": {
                "tags": [
                    "GitHub API"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "User kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Past GitHub Api key to perform request",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
